// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package game

import (
	"errors"
	"fmt"
)

const (
	// ActionIdle is a Action of type Idle.
	ActionIdle Action = iota + 1
	// ActionWalking is a Action of type Walking.
	ActionWalking
	// ActionAbility1 is a Action of type Ability1.
	ActionAbility1
	// ActionAbility2 is a Action of type Ability2.
	ActionAbility2
)

var ErrInvalidAction = errors.New("not a valid Action")

const _ActionName = "IdleWalkingAbility1Ability2"

var _ActionMap = map[Action]string{
	ActionIdle:     _ActionName[0:4],
	ActionWalking:  _ActionName[4:11],
	ActionAbility1: _ActionName[11:19],
	ActionAbility2: _ActionName[19:27],
}

// String implements the Stringer interface.
func (x Action) String() string {
	if str, ok := _ActionMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Action(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Action) IsValid() bool {
	_, ok := _ActionMap[x]
	return ok
}

var _ActionValue = map[string]Action{
	_ActionName[0:4]:   ActionIdle,
	_ActionName[4:11]:  ActionWalking,
	_ActionName[11:19]: ActionAbility1,
	_ActionName[19:27]: ActionAbility2,
}

// ParseAction attempts to convert a string to a Action.
func ParseAction(name string) (Action, error) {
	if x, ok := _ActionValue[name]; ok {
		return x, nil
	}
	return Action(0), fmt.Errorf("%s is %w", name, ErrInvalidAction)
}

const (
	// InputNone is a Input of type None.
	InputNone Input = iota
	// InputWalkLeft is a Input of type WalkLeft.
	InputWalkLeft
	// InputWalkRight is a Input of type WalkRight.
	InputWalkRight
)

var ErrInvalidInput = errors.New("not a valid Input")

const _InputName = "NoneWalkLeftWalkRight"

var _InputMap = map[Input]string{
	InputNone:      _InputName[0:4],
	InputWalkLeft:  _InputName[4:12],
	InputWalkRight: _InputName[12:21],
}

// String implements the Stringer interface.
func (x Input) String() string {
	if str, ok := _InputMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Input(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Input) IsValid() bool {
	_, ok := _InputMap[x]
	return ok
}

var _InputValue = map[string]Input{
	_InputName[0:4]:   InputNone,
	_InputName[4:12]:  InputWalkLeft,
	_InputName[12:21]: InputWalkRight,
}

// ParseInput attempts to convert a string to a Input.
func ParseInput(name string) (Input, error) {
	if x, ok := _InputValue[name]; ok {
		return x, nil
	}
	return Input(0), fmt.Errorf("%s is %w", name, ErrInvalidInput)
}
